### ISSUE TITLE
是否可以考虑加 排除某些属性的方法？

### ISSUE THREAD

**Issue by qinkangdeid** [dadiyang/equator#1]
是否可以考虑加 排除某些属性的方法？

比如User对象里都有id这个属性
一个是我数据库查出来的 带有id的值
另一个是我构造器出来的没有id的值
我只想对比除了id以外的其他属性值是否相等

**Comment by dadiyang** [comment]
现在是支持的。

```java
Equator equator = new GetterBaseEquator() {
    @Override
    protected boolean isFieldEquals(FieldInfo fieldInfo) {
        if ("id".equalsIgnoreCase(fieldInfo.getFieldName())) {
            return true;
        }
        return super.isFieldEquals(fieldInfo);
    }
};
equator.isEquals(user1, user2);
```

因为需要排除的情况各不相同，所以我留了这个 protected 方法可以自己扩展。

但是这样确实不优雅。我找时间再改进一下。

**Comment by qinkangdeid** [comment]
> 现在是支持的。
> 
> ```java
> Equator equator = new GetterBaseEquator() {
>     @Override
>     protected boolean isFieldEquals(FieldInfo fieldInfo) {
>         if ("id".equalsIgnoreCase(fieldInfo.getFieldName())) {
>             return true;
>         }
>         return super.isFieldEquals(fieldInfo);
>     }
> };
> equator.isEquals(user1, user2);
> ```
> 
> 因为需要排除的情况各不相同，所以我留了这个 protected 方法可以自己扩展。
> 
> 但是这样确实不优雅。我找时间再改进一下。

好的 谢谢~

**Comment by dadiyang** [comment]
新版本1.0.2 已经添加了这个功能。

```java
// 第一个参数设置只包含某些字段，第二个参数设置要排除的字段，为空则不限制
Equator equator = new GetterBaseEquator(null, Collections.singletonList("id"));
equator.isEquals(user1, user2);
```
